server:
  port: 8070
spring:
  datasource:
    url: jdbc:h2:mem:triple;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace